package ReCheck;

import java.io.IOException;
import java.util.Scanner;


public class Test10 {
    public int solution(int num) {
        int result = 0;


        return result;
    }

    public static void main(String[] args) throws IOException {
        Test10 T = new Test10();
        Scanner sc = new Scanner(System.in);
        int num = sc.nextInt();

        System.out.println(T.solution(num));
    }
}
