package ReCheck;

import java.io.IOException;
import java.util.Scanner;


public class Test13 {
    public int solution(int num, int[] arr) {
		int result=0;
		

        return result;
    }

    public static void main(String[] args) throws IOException {
        Test13 T = new Test13();
        Scanner sc = new Scanner(System.in);
        int num = sc.nextInt();

    }
}
